增加k2p

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -8,7 +8,7 @@
 # Description: Build OpenWrt using GitHub Actions
 #
 
-name: Build OpenWrt Single
+name: Build OpenWrt
 
 on:
   repository_dispatch:
@@ -101,6 +101,7 @@ jobs:
       
     - name: prinf machine info and matrix info
       run: |
+        uname -a
         df -h
         lscpu
         free -h
@@ -272,6 +273,7 @@ jobs:
         
         # 开启 imagebuilder 的话 保留一个.config.bak 给非 slim 使用
         if grep -Eq '^CONFIG_IB=y' .config;then
+          echo 'MAKE_OPTS=IGNORE_ERRORS=1' >> $GITHUB_ENV
           if [ "$NO_CACHE" != 1 ];then
             mv .config config.slim
             cat config.buildinfo > .config
@@ -286,6 +288,8 @@ jobs:
             sed -ri '/^CONFIG_PACKAGE_luci-app-[0-9a-z-]+=y/{s@^@# @;s@=y@ is not set@}' .config
             make defconfig
           fi
+        else
+          echo 'MAKE_OPTS=' >> $GITHUB_ENV
         fi
 
         if [ "$MakeDownload" == true ];then
@@ -323,12 +327,15 @@ jobs:
           # 6小时超时，减去上传 cache 预留的 10 分钟后的时间作为 timeout 时间
           timeoutSec=$(( 6*60*60 - 10*60 - $usedSec  ))
           # 初次没缓存用 timeout 后防止超时 action ，后面会上传缓存目录
-                # time make -j$(nproc) IGNORE_ERRORS=1 || make -j1 IGNORE_ERRORS=1 || make -j1 V=s IGNORE_ERRORS=1
-          echo timeout $timeoutSec make -j$(nproc) IGNORE_ERRORS=1
-          timeout $timeoutSec make -j$(nproc) IGNORE_ERRORS=1
-          # timeout 超时是 124 返回码
-          if [ $? -ne 0 -a $? -ne 124 ];then
-            make -j1 || make -j1 V=s
+          echo timeout $timeoutSec make -j$(nproc) $MAKE_OPTS
+          if ! timeout $timeoutSec make -j$(nproc) $MAKE_OPTS;then
+            # timeout 超时是 124 返回码
+            makeExit=$?
+            echo "timeout make exitcode: $makeExit"
+            if [ $makeExit -ne 0 -a $makeExit -ne 124 ];then
+              echo 'failed: try to V=s'
+              make -j1 || make -j1 V=s
+            fi
           fi
         else
           make -j$(nproc) || make -j1 || make -j1 V=s
@@ -572,7 +579,7 @@ jobs:
           mkdir -p files/local_feed && sudo mount --bind packages files/local_feed
           echo "suffix=-slim" >> $GITHUB_ENV
         else
-          echo "suffix=" >> $GITHUB_ENV
+          echo "suffix=-full" >> $GITHUB_ENV
         fi
 
         sed -i 's/luci-app-[^ ]*//g' include/target.mk $(find target/ -name Makefile)
